### ISSUE TITLE
[Minor] on quiz page it feels like there should be an option to select None for both dietary restriction and health goals so something has to be clicked before hitting submit

### ISSUE THREAD

**Issue by swaleha6** [info442-aut21/f-team#59]
[Minor] on quiz page it feels like there should be an option to select None for both dietary restriction and health goals so something has to be clicked before hitting submit

**Comment by swaleha6** [comment]
- in the selection section before hitting submit on the food quiz, it isn't required to select a option but I feel like it'd be more intuitive if there was an option to select None for both categories
- Firefox on Windows 10
- on quiz page looking at the food quiz 
- expected to have an option to select no dietary restrictions and no goals
- actual result: no option to select no dietary restrictions and no goals

**Comment by sershon** [comment]
It was a design choice to not have a "none" button for either of these selections. If you don't select any restrictions or goals, it is assumed that you don't have any. We will consider adding additional guidance to make it more clear. Thank you for reporting!

**Comment by cherimarie** [comment]
@swaleha6 for future reference, I would categorize this as an enhancement/feature request rather than a bug. The functionality does work as expected now, but you're suggesting the user experience could be improved.
