### ISSUE TITLE
[Major] Hash Menu doesn't work 

### ISSUE THREAD

**Issue by angelinapoltavskiy** [info442-aut21/f-team#60]
When I opened up the application on my screen, which is not full screen there is the hash menu, but when I click on it nothing happens.
Environment used: Google chrome - Version 95.0.4638.69 
Steps to reproduce: Open up google chrome browser, open up you application so that it's only half of the screen.
Expected result: when I click on hash menu, there is a dropdown menu , or nav bar of some sort
Actual result: when I click on hash menu, nothing happens

**Comment by ychen023** [comment]
I think there is a humbergur menu collapse bootstrap at the navlink piece code, not sure why it is not functining need to take a deeper look on and maybe rearrange the order of the humbergur bootstrap and some of the divs that includes the bootstrap code piece.

**Comment by sershon** [comment]
Fixed with latest pull request.
