### ISSUE TITLE
[Minor] Quiz Page: Not showing different results after selecting different filters

### ISSUE THREAD

**Issue by Jemuelle4** [info442-aut21/f-team#61]
Severity: Minor
Description: When choosing a different filter after submitting once, no new items pop up with the correct items when choosing a different filter. 
Environment: Windows 10 Firefox 94.0.1 (32-bit)
Steps to reproduce: Select filters and submit. Change the filters into different values and hit submit again.
Expected Results: Items with new applied filters should appear
Actual Result: Items stay the same based on the first selections

**Comment by ychen023** [comment]
Look into how props passed in first, and. then revise the functions as needed.

**Comment by cherimarie** [comment]
I believe this issue is effectively the same as https://github.com/info442-aut21/f-team/issues/81. One can be marked "duplicate" and closed, though both reporters will get credit.

**Comment by sershon** [comment]
Fixed in latest pull request.
