### ISSUE TITLE
[Major] Clicking on Logo leads to 404 page

### ISSUE THREAD

**Issue by ayun6** [info442-aut21/f-team#62]
Clicking on the Foodies logo on the upper left from any page leads to the page displaying 404 not found. 
Expected result: redirected back to home page from other pages on site.
Actual result: 404 page not found. 
Chrome 95.0.4638.69 on MacOS Big Sur

**Comment by ychen023** [comment]
Problems when switching around branches, the link get lost, quick fix if change the href for the website logo to / in the index.html file would fix it.

**Comment by cherimarie** [comment]
I think this is a minor level bug, as the site is still usable and all pages are accessible via nav bar.

**Comment by sershon** [comment]
Closed with change to netlify.
