### ISSUE TITLE
[Minor] macronutrients breakdown image not showing up

### ISSUE THREAD

**Issue by ayun6** [info442-aut21/f-team#64]
On the Quiz page of the application, scrolling just beneath Health Goals, there is an image labeled macronutrients breakdown but it is unviewable. 
Environment: Chrome 95.0.4638.69 on MacOS Big Sur
Expected result: displayed image
Actual result: no image 

<img width="948" alt="Screen Shot 2021-11-22 at 9 10 07 AM" src="https://user-images.githubusercontent.com/72246542/142904869-ed7f06f2-acc5-49d7-a6aa-a10d71623756.png">

**Comment by talajune** [comment]
Also not working on IPhone 12 Pro - Safari IOS v14.8
![IMG_7499](https://user-images.githubusercontent.com/76933462/142907207-38645f5a-345b-4ccd-959f-66ad46f0b347.PNG)

**Comment by sershon** [comment]
Thank you for reporting this! I'm not sure why this issue is occurring, but we've had some issues with images.

**Comment by cherimarie** [comment]
Inspecting this element, I can see that the image source is a relative path. In many compiled web apps, relative pathing won't work. This guide may provide the info needed: https://create-react-app.dev/docs/adding-images-fonts-and-files

<img width="426" alt="Screen Shot 2021-11-24 at 5 56 00 PM" src="https://user-images.githubusercontent.com/2523812/143363369-745c798a-e6dc-4495-af48-ab7909a83301.png">

**Comment by sershon** [comment]
Fixed with change to netlify.
