### ISSUE TITLE
[Major] Clicking on a recipe then going back to website leads to 404 error

### ISSUE THREAD

**Issue by meghajain2** [info442-aut21/f-team#66]
From the main page, when I click on "go to recipe", it takes me to a new page with the recipe. However, when I try to go back, the Foodie site shows a 404 error. 

Environment: Chrome Version 96.0.4664.55 on MacOS Big Sur
Steps to reproduce: From https://info442-aut21.github.io/f-team/, go to main page, click on any "go to recipe" for a given recipe which will redirect you to a new site, press the back button to return to the web app
Expected output: When the back arrow is pressed, the expected output was to return to the original page
Actual output: When the back arrow is pressed, the actual output is going to a 404 error page.

**Comment by sershon** [comment]
This is related to the issue we have been having with the ReDirectTo statements. We will be fixing those to re-render the page instead of trying to go back to an html link. Thank you for reporting.

**Comment by sershon** [comment]
Closed with change to netlify.
