### ISSUE TITLE
[Major] Cooking time filter doesn't work

### ISSUE THREAD

**Issue by victoriathegr8** [info442-aut21/f-team#67]
Upon submitting the quiz with a cooking time input, no filtering seems to happen with the recipes.
Chrome v96.0.4664.45 on Windows 10
1. Scroll on homepage to cooking time input box
2. Input 2 minutes
3. Press submit button
4. See filtered results
Expected results: see only recipes that take less than 2 minutes to make
Actual result: still recipes that take 10 minutes to make

**Comment by sershon** [comment]
We're not entirely sure why this is not working, as it was in a previous version. We will be fixing it though and thank you for reporting.

**Comment by cherimarie** [comment]
This is a major level bug, as there is no workaround that allows the filter to work.

**Comment by sershon** [comment]
It turns out that the filter works as intended. However, by the time you reported this the API had ran out of calls, and all of the recipes in the dummy data set take longer than 2 minutes. We will be adding an error message making it clear when the API runs out of calls.
