### ISSUE TITLE
[Enhancement] Nothing changes when you don't enter the quiz form and click submit

### ISSUE THREAD

**Issue by naishg** [info442-aut21/f-team#69]
Description: Sometimes you don't know which boxes (filters) have not been filled out. Indicating to users that these boxes (Filters) have been left blank will be helpful. A possible way to do this could be by indicating it via a message or by highlighting the box red.

**Comment by sershon** [comment]
Thank you for reporting. This is an intentional choice as users should be able to enter nothing in the boxes and have a default value assumed.

**Comment by cherimarie** [comment]
For @naishg's phase 7 grade, this should have been a bug, not a feature request. Counting it as such.
