### ISSUE TITLE
[Major] Search button on the Main Page is not functional

### ISSUE THREAD

**Issue by Sneha-8** [info442-aut21/f-team#72]
Description: When searching for something using a search bar on the main page, it takes me to a 404 error page.
Expected: The search bar is supposed to show results according to the keywords searched
Actual: The search bar when searched for somethings leads to an 404 error page.
Tested on Chrome Version 96.0.4664.55 (Official Build) on MacOs Catalina.

**Comment by IamSuperB4** [comment]
It correctly uses the search bar as a way to filter your recipes. It takes you to the 404 error page when you press Enter after you have typed something into the search bar.

ie: I typed "berry" into the search bar, pressed enter, and it brought be to this 404 page:
https://info442-aut21.github.io/f-team/main?search=Berry

**Comment by IamSuperB4** [comment]
I think this might count as another bug, though I don't know how much control you have over what the back button does. When you press the back button to get back from that 404 page after searching, it takes you to another 404 page:
https://info442-aut21.github.io/f-team/main

From here, pressing the back button seems to never take you back to your page no matter how many times you press it.

**Comment by julianedelossantos** [comment]
After reaching the 404 error page, trying to navigate back to a page(s) continue to show more 404 error pages. Once you hit that block, it doesn't matter what route is entered, the entire page gets blocked until you open up a new one.

At the very least, I expected the result to be able to go back to a working page when met with the initial 404.

To reproduce this issue, you can click on the main page navigation tab and type in the letter "s" under the recipe search bar, and hit "Enter". The first 404 page should show, but the expected result would either have been to stay on the same page and return some sort of error or show results of everything with the letter "s" within its recipe card. From this 404 page, you can click the back button on your browser to try and get back to the main page, but you will be met with another 404 error. If you try fixing the pathing in the URL to just "/main" again, it does not return you to the main page. The expected result was that it would return to the main page.

Environment: Windows 11 - Brave Browser: Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)

<img width="810" alt="image" src="https://user-images.githubusercontent.com/72470963/142915476-23c091e2-9452-4f2a-9802-8ba6f616bfda.png">

**Comment by sershon** [comment]
We believe this has to do with us not setting up the ReDirectTo handler properly. Thank you for reporting!
