### ISSUE TITLE
[Minor] All recipe cards on homepage quiz link to the same external recipe

### ISSUE THREAD

**Issue by victoriathegr8** [info442-aut21/f-team#73]
After filtering through the recipes for the quiz, the "GO TO RECIPE" button links to the same recipe, regardless of which recipe is actually clicked.
Chrome v96.0.4664.45 on Windows 10
1. Scroll down to recipes on quiz
2. Press Any "GO TO RECIPE" button that isn't on the "Immunity Booster Beet, Carrot & Orange Juice" card
Expected result: be taken to specific recipe for that card
Actual result: taken to recipe for the Immunity Booster Beet, Carrot & Orange Juice

**Comment by sershon** [comment]
We were able to recreate the step for two of the cards on the page, but only 2 (Snail Stew and Jambalaya) of the 10 recipes in that same search linked to the "Immunity Booster Beet, Carrot & Orange Juice". We have determined that this is an error from the Spoonacular API with the links they provided with those two recipes.

**Comment by cherimarie** [comment]
Interesting that it's an issue with the API! Good find. Have you reported it as a bug to them?
