### ISSUE TITLE
[Major] Hamburger menu on Phone Screen does not work

### ISSUE THREAD

**Issue by Preciousstowers** [info442-aut21/f-team#75]
When using a phone, the hamburger menu does not work/open. 

Device: iPhone 11 pro max on Chrome IOS 96.0.4664.53

Steps to reproduce: 
1. Go to home screen
2. Tap on the hamburger menu on a small mobile screen 
Actual: Tapped on the hamburger menu and nothing happened
Expected: Tapped on the hamburger menu and it displays the menu options

**Comment by Skylitmoon** [comment]
This is a duplicate issue of: https://github.com/info442-aut21/f-team/issues/60
