### ISSUE TITLE
[Minor] Wrong Image Sizes

### ISSUE THREAD

**Issue by nsnatthapat** [info442-aut21/f-team#76]
Image size does not fit container.

Environment: Version 95.0.4638.69 (Official Build) (x86_64) on MacOS Monterey 

Steps to Reproduce:
1. To to Main Page from NavBar
2. Scroll down to "Drunken Apple Cake"

Expected: The Image to fit container with rounded edges like other images
Actual: Image is smaller and does not fit the container

**Comment by ychen023** [comment]
Since the image are from the APIs, some of the picture is not on the right scale, if we forced it to fit the card image size like others, it will be really streched out which looks not good. There are only a few images that are out of the scale, so we will leave it as a won't fix.
