### ISSUE TITLE
[Major] App crashes after refreshing page

### ISSUE THREAD

**Issue by matthewputra** [info442-aut21/f-team#78]
Environment: Google Chrome Version 95.0.4638.69 (Official Build) (x86_64)
Steps to reproduce: From the main link, click the "Main Page" tab and then refresh the browser.
Expected result: site refresh to the main page tab
Actual result: site crashes
Error message:
404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

**Comment by ychen023** [comment]
Also check out <redirect> in the <switch> and routes thing for navlinks. That might fix it.

**Comment by sershon** [comment]
Closed with change to netlify.
