### ISSUE TITLE
Minor: Unable to go back to "about us" page after clicking Linkedin 

### ISSUE THREAD

**Issue by manyaj57** [info442-aut21/f-team#79]
Description: after going to linkedin, back button to page produces an error page
Steps to Reproduce:
1. Go to about us page
2. click "linkedin" button
3. click back arrow on browser tab

Expected: I expected the about us page to show up after clicking back
Actual:produces a 404 page not found error
Tested on ChromeVersion 96.0.4664.55 (Official Build) on MacOs Catalina

**Comment by IamSuperB4** [comment]
This appears to be an overarching problem with the back button, though I don't know how much control you have over what the back button does. When you press the back button to get back from that 404 page after searching or going to a page that isn't the f-team page, it takes you to 404 page, usually this one:
https://info442-aut21.github.io/f-team/main

From here, pressing the back button seems to never take you back to your page no matter how many times you press it. If you have a valid URL and you can copy-paste that link into a new tab, it works, but the back button alone will never take you back to a functional page. Interestingly the "Forward" button does work though when you are taken to a valid URL.

**Comment by sershon** [comment]
Thank you for reporting. This is indeed an issue across the site. I believe it is because we need to fix our ReDirectTo handlers. We will be updating those, and additionally setting the links to open in a new tab.

**Comment by cherimarie** [comment]
I wouldn't label this as "duplicate", but for the Foodie Team, it probably makes sense to just have a single issue for all of the crashing behavior related to back button and page refresh actions. I'm confident they're all being caused by the same bug.
