### ISSUE TITLE
[minor] linkedin buttons are inconsistant

### ISSUE THREAD

**Issue by manyaj57** [info442-aut21/f-team#80]
Description: The linkedin buttons all lead to the same users profile (Jesse)

Steps to Reproduce:
1. go to about us page
2. click linkedin button for Ha or John
3. Directed to Jesse linkedin page
4. 
5. Expected: I expected it to show the respective linkedin page for each team member
Actual:shows Jesse's linkedin for all members 
Tested on ChromeVersion 96.0.4664.55 (Official Build) on MacOs Catalina

**Comment by sershon** [comment]
Thank you for reporting! This was fixed at some point, but was lost in the merges along the way. We will update the links in those href spots. Thanks!
