### ISSUE TITLE
[Minor] Clicking on the "Berry Banana Breakfast Smoothie" Recipe leads to a general website

### ISSUE THREAD

**Issue by Preciousstowers** [info442-aut21/f-team#82]
Description: When clicking on "Berry Banana Breakfast Smoothie", it leads me to the general website for the recipe instead of the recipe itself

Environment: Chrome Version 96.0.4664.55 on MacOS Big Sur

Steps: Navigate to the recipe and click on the "Berry Banana Breakfast Smoothie"  recipe button
Actual results: takes me to this page - https://www.pinkwhen.com/recipe-index/
Expected Results: Takes me to the smoothie recipe

**Comment by sershon** [comment]
The links from recipes are from the Spoonacular API, and we have no control over what the link is. So I'm closing the issue with the wontfix tag, but really it is can't fix! Thanks for reporting.
