### ISSUE TITLE
[Minor] Clicking a blank quiz only returns 5 recipes

### ISSUE THREAD

**Issue by joonbot1999** [info442-aut21/f-team#86]
When I submit a blank quiz, it only returns the same 5 recipes as if I actually submitted a properly filled-out quiz. 
environment: Chrome Version 96.0.4664.45, Omen 15
steps to reproduce: submit a blank quiz
expected result: return all recipes on the main page
actual result: only returns 5 like it would do for regular quiz

**Comment by sershon** [comment]
The issue you encountered happens when the API runs out of calls, and we instead use dummy data to populate the search. We feel as though this is the smoothest way to handle the data. We will consider adding an additional error message to make that more clear though! Thanks for reporting.
