### ISSUE TITLE
Better Alt Tags on Recipe Images

### ISSUE THREAD

**Issue by Jemuelle4** [info442-aut21/f-team#91]
Currently, all the alt tags on the image in "Main Page" has the content "recipe". Is it possible to describe the image a bit better--perhaps make the alt tag the title of the recipe?

**Comment by Skylitmoon** [comment]
This is a really good suggestion! Unfortunately, our API does not include an alt tag for the images, so we can only add manually an alt tag (recipe) that would describe all images accurately.
